version: "3.1"


services:
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    volumes:
      - ../test:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1